baseurl = "https://stefanlaser.net/"
title = "Academic portfolio"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-uk"


[params]

defaultContentLanguage = 'en'

#defaultContentLanguageInSubdir = true

  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Academic portfolio"
  copyright = "&copy;2023"


  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "CV"
  url = "about/cv.html"

  [[params.navlinks]]
  name = "Legal"
  url = "legal/"


  #[[params.navlinks]]
  #name = "Get in touch"
  #url = "contact/"

  [languages]
    [languages.en]
      baseURL = 'https://stefanlaser.net/en'
      languageName = 'en'
      title = 'Stefan Laser'
      weight = 1
      languageFlag = "ðŸ‡¬ðŸ‡§"
      sidebarAbout = [
        "I am a sociologist interested in interdisciplinary and international collaboration. I contribute to Science and Technology Studies and publish on waste, energy, trains and meat. I am part of the newly established collaborative research centre 'Virtual Living Realities'",
        "My main theme right now is data centres: their local arrangement, building procedures, and global production networks enabling its operation.",
        "Currently based in Bochum. Working from Hanoi, Vietnam.",
        "Feel free to drop an e-mail or DM me."
      ]



    [languages.de]
      baseURL = 'https://stefanlaser.net/de'
      languageName = 'de'
      title = 'Stefan Laser'
      weight = 2
      languageFlag = "ðŸ‡©ðŸ‡ª"
      sidebarAbout = [
        "Ich bin Soziologe mit einem Faible fÃ¼r interdisziplinÃ¤re und internationale Problemstellungen. Ich knÃ¼pfe an die Science & Technology Studies an und schreibe zu E-Schrott, Energie, ZÃ¼gen und Fleisch. Ich bin Teil des neuen Bochumer SFBs 'Virtuelle Lebenswelten'",
        "Mein Hauptforschungsinteresse liegt zur Zeit auf Datenzentren: ihrer lokalen Ausrichtung, Erbauung, und globalen Produktionsnetzwerken.",
        "Aktuell arbeite ich in Bochum und lebe in Erfurt. Ich forsche und lebe aktuell in Hanoi, Vietnam."
      ]



  [params.social]
  email         = "stefan.laser@ruhr-uni-bochum.de"
  website       = "https://www.sfb1567.ruhr-uni-bochum.de/early-career-forum/xx-5"
  website2       = "https://www.sowi.ruhr-uni-bochum.de/cupak/team/laser.html.en"
  twitter       = "https://twitter.com/stefan_laser_"
  github        = "https://github.com/LaserStefan"
  mastodon      = "https://social.tchncs.de/@stefanlaser"

